# Python Basic Programming Assignment 8

### 1. Write a Python Program to Add Two Matrices?

In [13]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)


[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


### 2. Write a Python Program to Multiply Two Matrices?

In [12]:
import numpy as np
x = ([1,3,5],[4,2,6],[6,2,6])
y = ([4,2,5],[5,1,8],[9,2,5])

result = np.dot(x,y)
print(result)

[[64 15 54]
 [80 22 66]
 [88 26 76]]


### 3. Write a Python Program to Transpose a Matrix?

In [14]:
# Program to transpose a matrix using a nested loop

X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)


[12, 4, 3]
[7, 5, 8]



### 4. Write a Python Program to Sort Words in Alphabetic Order?


In [17]:
# Program to sort alphabetically the words form a string provided by the user

my_str = input("Enter a string: ")

# breakdown the string into a list of words
words = [word.lower() for word in my_str.split()]

# sort the list
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
   print(word)


Enter a string: hasg iuiugyuf ig ufjy
The sorted words are:
hasg
ig
iuiugyuf
ufjy


### 5. Write a Python Program to Remove Punctuation From a String?

In [18]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

# To take input from the user
my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)


Enter a string: hfyf6868699h=====[//']\[\iugy
hfyf6868699h=====iugy
